import{a as v,S,i as a}from"./assets/vendor-DqB7j7Ix.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const q="https://pixabay.com/api/",B="51379784-9fa8bd311ae31859cb2887282";async function u(s,t=1){const r={key:B,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await v.get(q,{params:r})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".load-more"),M=new S(".gallery a");function h(s){const t=s.map(r=>`
      <li class="gallery-item">
        <a href="${r.largeImageURL}">
          <img src="${r.webformatURL}" alt="${r.tags}" />
        </a>
        <div class="info">
          <p>Likes: ${r.likes}</p>
          <p>Views: ${r.views}</p>
          <p>Comments: ${r.comments}</p>
          <p>Downloads: ${r.downloads}</p>
        </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",t),M.refresh()}function P(){f.innerHTML=""}function p(){m.classList.remove("is-hidden")}function g(){m.classList.add("is-hidden")}function L(){y.classList.remove("is-hidden")}function w(){y.classList.add("is-hidden")}const b=document.querySelector(".form"),$=b.querySelector('input[name="search-text"]'),E=document.querySelector(".load-more");let n=1,i="",d=0;b.addEventListener("submit",async s=>{if(s.preventDefault(),i=$.value.trim(),!i){a.error({message:"Please enter a search term!"});return}n=1,P(),w(),p();try{const t=await u(i,n);d=t.totalHits,t.hits.length===0?a.info({message:"Sorry, no images found. Try again!"}):(h(t.hits),d>15&&L())}catch{a.error({message:"Error fetching images"})}finally{g()}});E.addEventListener("click",async()=>{n+=1,p(),w();try{const s=await u(i,n);h(s.hits);const t=Math.ceil(d/15);n<t?L():a.info({message:"We're sorry, but you've reached the end of search results."});const r=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}catch{a.error({message:"Failed to load more images"})}finally{g()}});
//# sourceMappingURL=index.js.map
